# ### Hyprland User Variables ###

# Apps
$terminal = ghostty
$browser = brave
$editor = codium
$fileExplorer = nautilus

# Gaps
$workspaceGaps = 10
$windowGapsIn = 5
$windowGapsOut = 10
$singleWindowGapsOut = 10

# Window styling
$windowOpacity = 1.0

# Keybinds
$kbTerminal = Super, Return
$kbBrowser = Super, B
$kbMoveWinToWs = Super+Shift
$kbMoveWinToWsGroup = Ctrl+Super+Shift

bind = Super, Y, fullscreenstate, 0 2
